### ISSUE TITLE
dubbo-admin 启动报错org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource [/WEB-INF/webx.xml]; nested exception is java.lang.IllegalArgumentException: Unknown flag 0x1000

### ISSUE THREAD

**Issue by huanzhang** [dubbo/dubbo-ops#14]
dubbo-admin版本2.0.0

02-Mar-2018 13:28:00.382 SEVERE [http-nio-8080-exec-24] org.apache.catalina.core.StandardContext.listenerStart Exception sending context│
 initialized event to listener instance of class [com.alibaba.citrus.webx.context.WebxContextLoaderListener]                            │
 org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource │
[/WEB-INF/webx.xml]; nested exception is java.lang.IllegalArgumentException: Unknown flag 0x1000                                        │
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)        │
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)          │
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)          │
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:│
174)                                                                                                                                    │
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:│
209)                                                                                                                                    │
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:│
180)

**Comment by huanzhang** [comment]
自己顶。。。

**Comment by huanzhang** [comment]
出这个错，是因为我的tomcat使用了JDK 1.9。切换回1.8后，问题就解决了
